const KNOWN_LEMMAS: Record<string, string> = {
  talking: 'talk',
  talked: 'talk',
  dressed: 'dress',
  heard: 'hear',
  hummed: 'hum',
  children: 'child',
  went: 'go',
  gone: 'go',
  written: 'write',
  keeping: 'keep',
  whispering: 'whisper',
  running: 'run',
  making: 'make',
  made: 'make',
  taken: 'take',
  taking: 'take',
  seen: 'see',
  seeing: 'see',
  spoken: 'speak',
  speaking: 'speak',
  are: 'be',
  am: 'be',
  is: 'be',
  was: 'be',
  were: 'be',
  being: 'be',
  been: 'be',
  had: 'have',
  has: 'have',
  did: 'do',
  does: 'do',
  doing: 'do',
  saw: 'see',
  said: 'say',
  thought: 'think',
  brought: 'bring',
  bought: 'buy',
  caught: 'catch',
  taught: 'teach',
  knew: 'know',
  told: 'tell',
  found: 'find',
  gave: 'give',
  got: 'get',
  took: 'take',
  came: 'come',
  ran: 'run',
  felt: 'feel',
  left: 'leave',
  wrote: 'write',
  began: 'begin',
  became: 'become',
  broke: 'break',
  built: 'build',
  chose: 'choose',
  drew: 'draw',
  drank: 'drink',
  drove: 'drive',
  ate: 'eat',
  fell: 'fall',
  flew: 'fly',
  forgot: 'forget',
  grew: 'grow',
  held: 'hold',
  kept: 'keep',
  led: 'lead',
  lost: 'lose',
  met: 'meet',
  paid: 'pay',
  rode: 'ride',
  rang: 'ring',
  rose: 'rise',
  sold: 'sell',
  sent: 'send',
  slept: 'sleep',
  spent: 'spend',
  stole: 'steal',
  swam: 'swim',
  threw: 'throw',
  woke: 'wake',
  wore: 'wear',
  won: 'win',
};

/**
 * Conservative fallback lemma.
 * This function intentionally does NOT guess ambiguous -s forms such as
 * "leaves" because they can be either a plural noun or a verb.
 * Context-aware normalization happens in wordlookup.ts.
 */
export function getLemma(word: string): string {
  const normalized = word.toLowerCase().replace(/[^a-z'-]/g, '');
  if (!normalized) return word;
  return KNOWN_LEMMAS[normalized] || normalized;
}
